public static class ItemCollections
{
	public static ItemModel[][] Levels =
	[
		[ // 1
			ModelDB.Item<AmuletOfLife>(),
			ModelDB.Item<CircletOfElements>(),
			ModelDB.Item<HideArmor>(),
			ModelDB.Item<LeatherArmor>(),
			ModelDB.Item<WeatheredBoots>(),
			ModelDB.Item<WingedShoes>(),
			ModelDB.Item<ShoesOfHappiness>(),
			ModelDB.Item<BootsOfSpeed>(),
			ModelDB.Item<HeaterShield>(),
			ModelDB.Item<PoisonDagger>(),
			ModelDB.Item<HookedChain>(),
			ModelDB.Item<IronSpear>(),
			ModelDB.Item<MinorHealingPotion>(),
			ModelDB.Item<MinorPowerPotion>(),
			ModelDB.Item<MinorManaPotion>(),
		],
		[ // 2
			// ModelDB.Item<HornedHelm>(),
			// ModelDB.Item<HawkHelm>(),
			// ModelDB.Item<RobesOfSummoning>(),
			// ModelDB.Item<HeavyGreaves>(),
			ModelDB.Item<WeightedNet>(),
			// ModelDB.Item<FueledFalchion>(),
			// ModelDB.Item<MinorCurePotion>(),
			// ModelDB.Item<OakCharm>(),
		],
		[ // 3
			ModelDB.Item<IronHelmet>(),
			// ModelDB.Item<Chainmail>(),
			// ModelDB.Item<StuddedLeather>(),
			ModelDB.Item<BootsOfStriding>(),
			// ModelDB.Item<JaggedSword>(),
			ModelDB.Item<BattleAxe>(),
			// ModelDB.Item<ThrowingHammer>(),
			ModelDB.Item<MinorStaminaPotion>(),
			ModelDB.Item<StunPowder>(),
			// ModelDB.Item<FatefulCompass>(),
		],
		[ // 4
			ModelDB.Item<EagleEyeGoggles>(),
			// ModelDB.Item<SacrificialRobes>(),
			// ModelDB.Item<ConfortableShoes>(),
			// ModelDB.Item<BlackKnife>(),
			// ModelDB.Item<TowerShield>(),
			ModelDB.Item<PiercingBow>(),
			// ModelDB.Item<ReapingScythe>(),
			// ModelDB.Item<MoonEarring>(),
			// ModelDB.Item<MajorHealingPotion>(),
			// ModelDB.Item<FalconFigurine>(),
		],
		[ // 5
			ModelDB.Item<EmpoweringTalisman>(),
			// ModelDB.Item<Splintmail>(),
			// ModelDB.Item<ShadowArmor>(),
			// ModelDB.Item<SteelSabatons>(),
			ModelDB.Item<WarHammer>(),
			// ModelDB.Item<VersatileDagger>(),
			// ModelDB.Item<BlackCandle>(),
			// ModelDB.Item<MajorManaPotion>(),
			// ModelDB.Item<MajorCurePotion>(),
			// ModelDB.Item<RingOfStrength>(),
		],
		[ // 6
			// ModelDB.Item<ProtectiveCharm>(),
			ModelDB.Item<CloakOfPockets>(),
			// ModelDB.Item<BootsOfDashing>(),
			// ModelDB.Item<BootsOfQuickness>(),
			// ModelDB.Item<SpikedShield>(),
			// ModelDB.Item<StaffOfEminence>(),
			ModelDB.Item<WandOfFrost>(),
			ModelDB.Item<WandOfStorms>(),
			ModelDB.Item<WandOfInfernos>(),
			ModelDB.Item<WandOfTremors>(),
			ModelDB.Item<WandOfBrilliance>(),
			ModelDB.Item<WandOfDarkness>(),
			// ModelDB.Item<MajorPowerPotion>(),
			// ModelDB.Item<SunEarring>(),
		],
		[ // 7
			// ModelDB.Item<MaskOfTerror>(),
			ModelDB.Item<CloakOfInvisibility>(),
			// ModelDB.Item<Platemail>(),
			// ModelDB.Item<SereneSandals>(),
			// ModelDB.Item<VolatileBomb>(),
			// ModelDB.Item<WallShield>(),
			// ModelDB.Item<AncientDrill>(),
			// ModelDB.Item<SuperHealingPotion>(),
			// ModelDB.Item<MajorStaminaPotion>(),
			// ModelDB.Item<RingOfHaste>(),
		],
		[ // 8
			// ModelDB.Item<TelescopicLens>(),
			// ModelDB.Item<RobesOfEvocation>(),
			// ModelDB.Item<BootsOfLevitation>(),
			// ModelDB.Item<Halberd>(),
			// ModelDB.Item<FrigidBlade>(),
			// ModelDB.Item<StormBlade>(),
			// ModelDB.Item<InfernoBlade>(),
			// ModelDB.Item<TremorBlade>(),
			// ModelDB.Item<BrilliantBlade>(),
			// ModelDB.Item<NightBlade>(),
			// ModelDB.Item<DoomPowder>(),
			// ModelDB.Item<LuckyEye>(),
			// ModelDB.Item<RingOfBrutality>(),
		],
		[ // 9
			// ModelDB.Item<PendantOfDarkPacts>(),
			// ModelDB.Item<CloakOfPhasing>(),
			// ModelDB.Item<RocketBoots>(),
			// ModelDB.Item<BootsOfSprinting>(),
			// ModelDB.Item<LongSpear>(),
			// ModelDB.Item<UnstableExplosives>(),
			// ModelDB.Item<BalancedBlade>(),
			// ModelDB.Item<StarEarring>(),
			// ModelDB.Item<SecondChanceRing>(),
		],
	];

	public static ItemModel[] Random =
	[
		// ModelDB.Item<HeavyBasinet>(),
		// ModelDB.Item<ChainHood>(),
		ModelDB.Item<NecklaceOfTeeth>(),
		// ModelDB.Item<DrakescaleHelm>(),
		// ModelDB.Item<ThiefsHood>(),
		// ModelDB.Item<HelmOfTheMountain>(),
		// ModelDB.Item<WaveCrest>(),
		//
		// ModelDB.Item<BlinkingCape>(),
		// ModelDB.Item<SwordedgeArmor>(),
		// ModelDB.Item<SecondSkin>(),
		// ModelDB.Item<DrakescaleArmor>(),
		// ModelDB.Item<SteamArmor>(),
		// ModelDB.Item<FleaBittenShawl>(),
		// ModelDB.Item<RobesOfCommand>(),
		//
		// ModelDB.Item<EnduranceFootwraps>(),
		// ModelDB.Item<DrakescaleBoots>(),
		// ModelDB.Item<MagmaWaders>(),
		// ModelDB.Item<JetBoots>(),
		//
		// ModelDB.Item<SkullbaneAxe>(),
		// ModelDB.Item<StaffOfXorn>(),
		// ModelDB.Item<MountainHammer>(),
		// ModelDB.Item<StaffOfElements>(),
		// ModelDB.Item<BloodyAxe>(),
		// ModelDB.Item<StaffOfSummoning>(),
		// ModelDB.Item<SkullOfHatred>(),
		// ModelDB.Item<OrbOfDawn>(),
		// ModelDB.Item<OrbOfTwilight>(),
		// ModelDB.Item<BarbedAxe>(),
		//
		// ModelDB.Item<SteelRing>(),
		// ModelDB.Item<DampeningRing>(),
		// ModelDB.Item<ScrollOfPower>(),
		// ModelDB.Item<ScrollOfHealing>(),
		// ModelDB.Item<ScrollOfStamina>(),
		// ModelDB.Item<RingOfSkulls>(),
		// ModelDB.Item<DoomedCompass>(),
		// ModelDB.Item<CuriousGear>(),
		// ModelDB.Item<RemoteSpider>(),
		// ModelDB.Item<GiantRemoteSpider>(),
		// ModelDB.Item<BlackCenser>(),
		// ModelDB.Item<BlackCard>(),
		// ModelDB.Item<HelixRing>(),
		// ModelDB.Item<HeartOfTheBetrayer>(),
		// ModelDB.Item<PowerCore>(),
		// ModelDB.Item<ResonantCrystal>(),
	];
}