public static partial class BattleGoals
{
	public static BattleGoalModel[] Goals { get; } =
	[
		ModelDB.BattleGoal<Accountant>(),
		ModelDB.BattleGoal<Acrobat>(),
		ModelDB.BattleGoal<Ascetic>(),
		ModelDB.BattleGoal<Assassin>(),
		ModelDB.BattleGoal<Assistant>(),
		ModelDB.BattleGoal<Bastion>(),
		ModelDB.BattleGoal<Bully>(),
		ModelDB.BattleGoal<Cleaner>(),
		ModelDB.BattleGoal<Closer>(),
		ModelDB.BattleGoal<Conservator>(),

		ModelDB.BattleGoal<Daredevil>(),
		ModelDB.BattleGoal<Dawdler>(),
		ModelDB.BattleGoal<Diehard>(),
		ModelDB.BattleGoal<Duelist>(),
		ModelDB.BattleGoal<Dynamo>(),
		ModelDB.BattleGoal<Egoist>(),
		ModelDB.BattleGoal<Executioner>(),
		ModelDB.BattleGoal<Exterminator>(),
		ModelDB.BattleGoal<Gambler>(),
		ModelDB.BattleGoal<Hunter>(),

		ModelDB.BattleGoal<Insomniac>(),
		ModelDB.BattleGoal<Layabout>(),
		ModelDB.BattleGoal<Masochist>(),
		ModelDB.BattleGoal<Miser>(),
		ModelDB.BattleGoal<Mugger>(),
		ModelDB.BattleGoal<Opener>(),
		ModelDB.BattleGoal<Optimist>(),
		ModelDB.BattleGoal<Overachiever>(),
		ModelDB.BattleGoal<Pacifist>(),
		ModelDB.BattleGoal<Pauper>(),

		ModelDB.BattleGoal<Peacemonger>(),
		ModelDB.BattleGoal<Pedestrian>(),
		ModelDB.BattleGoal<Perfectionist>(),
		ModelDB.BattleGoal<Pickpocket>(),
		ModelDB.BattleGoal<Pincushion>(),
		ModelDB.BattleGoal<Plebeian>(),
		ModelDB.BattleGoal<Prepper>(),
		ModelDB.BattleGoal<Prohibitionist>(),
		ModelDB.BattleGoal<Promoter>(),
		ModelDB.BattleGoal<Rambler>(),

		ModelDB.BattleGoal<Ravager>(),
		ModelDB.BattleGoal<Recluse>(),
		ModelDB.BattleGoal<Ritualist>(),
		ModelDB.BattleGoal<Sadist>(),
		ModelDB.BattleGoal<Scrambler>(),
		ModelDB.BattleGoal<Shirker>(),
		ModelDB.BattleGoal<Slayer>(),
		ModelDB.BattleGoal<Sleeper>(),
		ModelDB.BattleGoal<Slowpoke>(),
		ModelDB.BattleGoal<Sluggard>(),

		ModelDB.BattleGoal<Specialist>(),
		ModelDB.BattleGoal<Straggler>(),
		ModelDB.BattleGoal<Streamliner>(),
		ModelDB.BattleGoal<Tormentor>(),
		ModelDB.BattleGoal<Vanguard>(),
		ModelDB.BattleGoal<Wallflower>(),
		ModelDB.BattleGoal<Wastrel>(),
		ModelDB.BattleGoal<Weakling>(),
		ModelDB.BattleGoal<Workhorse>(),
		ModelDB.BattleGoal<Zealot>(),
	];
}