public static partial class BattleGoals
{
	public static BattleGoalModel[] Goals { get; } =
	[
		ModelDB.BattleGoal<Acrobatic>(),
		ModelDB.BattleGoal<Aggressor>(),
		ModelDB.BattleGoal<Ambusher>(),
		ModelDB.BattleGoal<Assassin>(),
		ModelDB.BattleGoal<Assistant>(),
		ModelDB.BattleGoal<Bastion>(),
		ModelDB.BattleGoal<Bully>(),
		ModelDB.BattleGoal<Contagious>(),
		ModelDB.BattleGoal<Covetous>(),
		// ModelDB.BattleGoal<Cuddler>(),
		ModelDB.BattleGoal<Diehard>(),
		ModelDB.BattleGoal<Discriminating>(),
		ModelDB.BattleGoal<Distracted>(),
		// ModelDB.BattleGoal<Drowsy>(),
		// ModelDB.BattleGoal<Dynamo>(),
		// ModelDB.BattleGoal<Elitist>(),
		// ModelDB.BattleGoal<Executioner>(),
		// ModelDB.BattleGoal<Explorer>(),
		// ModelDB.BattleGoal<Exterminator>(),
		// ModelDB.BattleGoal<FastHealer>(),
		// ModelDB.BattleGoal<Fearful>(),
		// ModelDB.BattleGoal<Feeble>(),
		// ModelDB.BattleGoal<Feral>(),
		// ModelDB.BattleGoal<Finisher>(),
		// ModelDB.BattleGoal<Hesitant>(),
		// ModelDB.BattleGoal<Hoarder>(),
		// ModelDB.BattleGoal<Hothead>(),
		// ModelDB.BattleGoal<Hunter>(),
		// ModelDB.BattleGoal<Indigent>(),
		// ModelDB.BattleGoal<Instigator>(),
		// ModelDB.BattleGoal<Insulting>(),
		// ModelDB.BattleGoal<Layabout>(),
		// ModelDB.BattleGoal<Limping>(),
		// ModelDB.BattleGoal<Lucky>(),
		// ModelDB.BattleGoal<Marksman>(),
		// ModelDB.BattleGoal<Masochist>(),
		// ModelDB.BattleGoal<Miser>(),
		// ModelDB.BattleGoal<Mugger>(),
		// ModelDB.BattleGoal<Multitasker>(),
		//
		// ModelDB.BattleGoal<Neutralizer>(),
		// ModelDB.BattleGoal<Opener>(),
		// ModelDB.BattleGoal<Pacifist>(),
		// ModelDB.BattleGoal<Paranoid>(),
		// ModelDB.BattleGoal<Peacemonger>(),
		// ModelDB.BattleGoal<Perforated>(),
		// ModelDB.BattleGoal<Pickpocket>(),
		// ModelDB.BattleGoal<Pincushion>(),
		// ModelDB.BattleGoal<Plunderer>(),
		// ModelDB.BattleGoal<Professional>(),
		// ModelDB.BattleGoal<Prosperous>(),
		// ModelDB.BattleGoal<Protector>(),
		// ModelDB.BattleGoal<Purist>(),
		// ModelDB.BattleGoal<Ravager>(),
		// ModelDB.BattleGoal<Recluse>(),
		// ModelDB.BattleGoal<Reserved>(),
		// ModelDB.BattleGoal<Restless>(),
		// ModelDB.BattleGoal<Retaliator>(),
		// ModelDB.BattleGoal<Ritualistic>(),
		// ModelDB.BattleGoal<Sadist>(),
		// ModelDB.BattleGoal<Scavenger>(),
		// ModelDB.BattleGoal<Scrambler>(),
		// ModelDB.BattleGoal<Shadow>(),
		// ModelDB.BattleGoal<Sharpshooter>(),
		// ModelDB.BattleGoal<Slayer>(),
		// ModelDB.BattleGoal<Sleepless>(),
		// ModelDB.BattleGoal<Sober>(),
		// ModelDB.BattleGoal<Sociable>(),
		// ModelDB.BattleGoal<Specialist>(),
		// ModelDB.BattleGoal<Stalwart>(),
		// ModelDB.BattleGoal<Straggler>(),
		// ModelDB.BattleGoal<Streamliner>(),
		// ModelDB.BattleGoal<Stubborn>(),
		// ModelDB.BattleGoal<Thorough>(),
		// ModelDB.BattleGoal<Untouchable>(),
		// ModelDB.BattleGoal<Wasteful>(),
		// ModelDB.BattleGoal<Winded>(),
		// ModelDB.BattleGoal<Workhorse>(),
		// ModelDB.BattleGoal<Zealot>(),
	];
}